server:
  port: 12001
# ===============================
# DATABASE
# ===============================

#spring.datasource.url=jdbc:mysql://restaurant-model.cevhtxtrp4c6.us-west-2.rds.amazonaws.com:3306/restaurant_model
#spring.datasource.username=admin
#spring.datasource.password=adminlta
spring:
  data:
    mongodb:
      database: mango
      host: 34.220.142.46
      port: 27017
      username: lee
      password: leelee22
#Security
security:
  oauth2:
    client:
      registration:
        google:
          clientId: 403326864709-f23bvkcipi31ijsba5ebd2e920h53l13.apps.googleusercontent.com
          clientSecret: '6hInnGYtQd07J_WqWQzR-l_E'
          redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - email
            - profile
        facebook:
          clientId: 121189305185277
          clientSecret: 42ffe5aa7379e8326387e0fe16f34132
          redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - email
            - public_profile
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect


#spring.data.mongodb.database=Mango
#spring.data.mongodb.host=192.168.0.94
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=lee
#spring.data.mongodb.password=leelee22


# ===============================
# JPA / HIBERNATE
# ===============================

#spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driverClassName=com.mysql.jdbc.Driver

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
#spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

# ===============================
# Thymeleaf
# ===============================
#spring.thymeleaf.templateResolverOrder=1

#logging.level.org.springframework.web=DEBUG

#logging.level.root=DEBUG




#Managment

#management.server.port=13000
#management.endpoints.web.exposure.include=*
#management.endpoint.shutdown.enabled=true
